; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24213.1 

	TITLE	C:\Users\Елена\Desktop\zlib-1.2.11\inffast.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

END
